### ISSUE TITLE
当我使用ajax形式将kindeditor加载到modal中时，只能显示普通文本框

### ISSUE THREAD

**Issue by DevinHe** [Macrow/rails_kindeditor#74]
我尝试了3种方式使用kindeditor
1.独立页面使用，正常
2.独立页面使用modal形式，正常
3.ajax形式，浏览器控制台没有js报错信息，但是无法正常加载

请教一下，这个可能是哪里的原因？

**Comment by Macrow** [comment]
你在js控制台里看看能不能手动加载kindeditor，ajax加载应该是没有问题的，请检查一下你的家在代码有没有问题，如果是纯javascript问题，可以到kindeditor的官方git去咨询一下。
