### ISSUE TITLE
quickformat.js导致rake aborted错误

### ISSUE THREAD

**Issue by air-wang** [Macrow/rails_kindeditor#77]
你好，我在部署过程中 bundle exec rake assets:precompile RAILS_ENV=production过程中出现错误，如下：
rake aborted!
TypeError: unknown filter type: #Pathname:kindeditor/plugins/quickformat/quickformat.js
谢谢！

**Comment by plusor** [comment]
https://github.com/Macrow/rails_kindeditor/pull/76
