### ISSUE TITLE
如果我有多个表都会用到Kindeditor   这时候Owerid  要怎么区分

### ISSUE THREAD

**Issue by m446883859** [Macrow/rails_kindeditor#80]
如果我有多个表都会用到Kindeditor   这时候Owerid  要怎么区分，

**Comment by Macrow** [comment]
请表述准确

**Comment by m446883859** [comment]
Thanks for your reply;

比如我有产品，产品会有一个详细的描述字段  这个使用KindEditor 来实现
同时我又有活动，活动详情的字段，  也用KindEditor实现，   
同一个系统里我有多个地方 多个表使用到KindEditor 这时候图片kindeditor_assets.owner_id   会出现重复，并且无法区分是产品的图片还是，还是活动详情的图片，

**Comment by Macrow** [comment]
确实之前没有考虑到这个问题，我已经更新了版本，加入了新字段，你这个问题我测试可以解决了，而且onwer的指定方式我作了简化，详细看下面的说明，我更新过了。

https://github.com/Macrow/rails_kindeditor/commit/d51521020b199cdecc7e7bbe9b2dc2ada29fcbce

ps:好久没动手写代码了，感觉有点生疏啊。

**Comment by m446883859** [comment]
Thanks for your reply;

我们的系统现在已经存在，并且正在运营，所以我们需要一个可以有效的升级方案，但是我尝试过现有个包有数据被清空掉的风险。

**Comment by Macrow** [comment]
这个升级不难吧，需要自己针对代码进行小心更改，这次更新rails_kindeditor对数据库的更改只是在asset数据表里加了一个字段，你完全可以自己后期手动加入，再用新的代码即可。

至于已经上传的附件，可能涉及到新字段数据空白的问题可能比较难办，可考虑暂时不用管，或者对于这批遗留数据可采取特殊处理手段。

**Comment by m446883859** [comment]
目前看来也只能如此了，非常感谢你的支持
