### ISSUE TITLE
每次按回车换行，会自动跳到段首。

### ISSUE THREAD

**Issue by gxlonline** [Macrow/rails_kindeditor#82]
当内容比较多，右侧显示滚动条后，每次会自动跳到最前面去，又得自己手动拉下来，请问怎么设置。
我看官网的demo没有这个问题。
V0.4.5
能否帮忙解决一下，谢谢了。

**Comment by Macrow** [comment]
我试过了，没有这个问题啊，是不是浏览器的问题？

而且我对官方的js代码基本没有改动，只是对路径稍作了调整，你再调试一下试试看。
