### ISSUE TITLE
carrierwave v0.11.2 已经发布，Carrierwave::MimeType 要废弃了

### ISSUE THREAD

**Issue by bastengao** [Macrow/rails_kindeditor#83]
asset_uploader.rb require 了 'carrierwave/processing/mime_types' 但是有没有在 AssetUploader 中 include `Carrierwave::MimeType`. https://github.com/Macrow/rails_kindeditor/blob/master/app/uploaders/kindeditor/asset_uploader.rb#L3

``` ruby
require 'carrierwave/processing/mime_types'

class Kindeditor::AssetUploader < CarrierWave::Uploader::Base
  # 没有 include , 所以上面 require 了也没用到
  # include CarrierWave::MimeTypes

  EXT_NAMES = {:image => RailsKindeditor.upload_image_ext,
               :flash => RailsKindeditor.upload_flash_ext,
               :media => RailsKindeditor.upload_media_ext,
               :file  => RailsKindeditor.upload_file_ext}
```

CarrierWave 可以直接使用 uploader.content_type, 提交在[这里](https://github.com/carrierwaveuploader/carrierwave/commit/992983d56e811fced8770ee73aed81799559b121)。

我看唯一用到地方是 [Assets](https://github.com/Macrow/rails_kindeditor/blob/master/lib/generators/rails_kindeditor/migration/templates/models/active_record/kindeditor/asset.rb#L11) model 里。

``` ruby
  def update_asset_attributes
    if asset.present? && asset_changed?
      self.file_size = asset.file.size
      self.file_type = asset.file.content_type
    end
  end
```

建议删掉 `require 'carrierwave/processing/mime_types'` 这行。

**Comment by Macrow** [comment]
删掉  require 'carrierwave/processing/mime_types'  后不影响使用吗？

**Comment by bastengao** [comment]
> CarrierWave::Utilities::Deprecation.new "0.11.0", "CarrierWave::MimeTypes is deprecated and will be removed in the future, get the content_type from the SanitizedFile object directly."

https://github.com/carrierwaveuploader/carrierwave/blob/v0.11.2/lib/carrierwave/processing/mime_types.rb#L30
