### ISSUE TITLE
导致skip_before_action :verify_authenticity_token has not been defined

### ISSUE THREAD

**Issue by yanchengv** [Macrow/rails_kindeditor#88]
rails5中加入这个gem后，会导致
`skip_before_action :verify_authenticity_token has not been defined`

**Comment by Macrow** [comment]
我这里测试一切正常啊，请再详细查看到底哪里出了问题。

**Comment by Yohansun** [comment]
我也出现了这个问题

**Comment by Macrow** [comment]
在assets_controller.rb里使用了

```ruby
class Kindeditor::AssetsController < ApplicationController
  skip_before_action :verify_authenticity_token
  ......
```

这个方法的定义在 ActionController::RequestForgeryProtection 里面，请再详细看看日志，找找看问题出在哪里。

**Comment by yangbo1987** [comment]
我用的 rails 5.1.2 出现
undefined method `skip_before_filter' for Kindeditor::AssetsController:Class Did you mean? skip_before_action

**Comment by Macrow** [comment]
看看rails_kindeditor的版本，是不是引用的老版本?

老版本原来是用的是`skip_before_filter`，但后来的版本已经改为`skip_before_action`

https://github.com/Macrow/rails_kindeditor/commit/00fb549580d1d135cb7a896360d4795e1ef930e1

**Comment by gxlonline** [comment]
rails 5.1.3 同样出现
undefined method `skip_before_filter' for Kindeditor::AssetsController:Class Did you mean? skip_before_action
rails_kindeditor 版本 0.5.0

**Comment by Martin288** [comment]
@Macrow 你是不是在 0.5.0 之后才修复的，我看你的修复的 commit 的时间在你 release 0.5.0 之后

### 发布0.5.0 时间在 Nov 2, 2016
![image](https://user-images.githubusercontent.com/13233606/32602821-8b49e776-c582-11e7-88dc-5614c25e0b32.png)

### 修复 skip_before_filter 问题在 Nov 18, 2016
![image](https://user-images.githubusercontent.com/13233606/32602807-81ba7b4e-c582-11e7-9f16-0f3bd006cabf.png)

**Comment by Macrow** [comment]
@Martin288 确实是这样，谢谢你帮我找到错误。-_-

这个问题在0.5.1的版本里更正了，请更新版本，给大家带来不便敬请谅解。

另外，由于Rails5.1已经放弃了jquery-rails，而rails_kindeditor需要使用，请在gemfile里加入jquery-rails。

```ruby
gem 'jquery-rails'
```
