### ISSUE TITLE
carrierwave 问题

### ISSUE THREAD

**Issue by caicai89** [Macrow/rails_kindeditor#91]
Hi， 我现在是rails5，但是在上传的时候报错
`LoadError - cannot load such file -- carrierwave/processing/mime_types:
   () Users/freda/.rvm/gems/ruby-2.2.2@global/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
   () Users/freda/.rvm/gems/ruby-2.2.2@global/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'`

但是  carrierwave  已弃用这个文件，改用 mime-type Gem 了。
这个怎么解决呢？谢谢

**Comment by Macrow** [comment]
我这里测试没有发现这个错误，你看看rails_kindeditor的版本对不对。

**Comment by caicai89** [comment]
【尴尬脸】 谢谢回复，我发了后，然后又自己删了Gemfile.lock ，去掉了自己添加的carrierwave gem。重新bundle 了一遍，就正常了~~~ 所以就直接close 了！

**Comment by Macrow** [comment]
欢迎多交流，多指教。
