### ISSUE TITLE
修改upload 为oss地址，结果还是上传到本地

### ISSUE THREAD

**Issue by dogsimple** [Macrow/rails_kindeditor#93]
是这样我想把我上传的视频，图片等上传到阿里oss上，于是修改了config.upload_dir为oss地址，但是并不能上传到oss，求怎么使上传的视频等文件上传到oss呢

**Comment by Macrow** [comment]
这个我没有试验过，不过看你的需求，估计要用到carrierwave-aliyun才能达到目的，你可以尝试添加这个gem来试一下，rails_kindeditor本身是用carrierwave来实现上传的，配合carrierwave-aliyun应该可以实现你的需求。

**Comment by dogsimple** [comment]
好的，谢谢了

2017-08-08 20:59 GMT+08:00 Macrow <notifications@github.com>:

**Comment by dogsimple** [comment]
我安装了carrierwave-aliyun，并且配置了oss的配置，但是上传路径还是upload文件夹下，是不是 kindeditor的上传路径也需要相应的修改一下啊

**Comment by clownf** [comment]
在 rails_kindeditor 下该如何配置？
