### ISSUE TITLE
zh-CN to zh-TW

### ISSUE THREAD

**Issue by louis70109** [Macrow/rails_kindeditor#96]
您好：
我在rails下使用了<%= f.kindeditor :content, simple_mode: true, langType: "zh-TW" %>
將語言切換成 TW
console下也有顯示取用zh-TW.js 
但網頁的輸入框依舊是zh-CN
能請問大神有解的嗎？

**Comment by Macrow** [comment]
如果只用繁体，可以直接把zh-CN.js文件换成繁体字的内容。
